<?php

/**
 * ContactArchiveTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContactArchiveTable extends PluginContactArchiveTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContactArchiveTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ContactArchive');
    }
}