<?php

/**
 * ContactRelationshipTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContactRelationshipTypeTable extends PluginContactRelationshipTypeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContactRelationshipTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ContactRelationshipType');
    }
}