<?php

/**
 * ContactPhonenumberTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContactPhonenumberTable extends PluginContactPhonenumberTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContactPhonenumberTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ContactPhonenumber');
    }
}