<?php

/**
 * ContactRelationship
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Baptiste SIMON <baptiste.simon AT e-glop.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ContactRelationship extends PluginContactRelationship
{
  public function __toString()
  {
    return $this->Contact.' ('.$this->Type.')';
  }
  public function getUrl()
  {
    sfApplicationConfiguration::getActive()->loadHelpers(array('CrossAppLink'));
    if ( $this->to_contact_id )
      return cross_app_url_for('rp','contact/show?id='.$this->to_contact_id);
    return '';
  }
}
