<?php

/**
 * ContactTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContactTable extends PluginContactTable
{
  public function retreiveList()
  {
    return $this->createQuery('c')
      ->leftJoin('o.Phonenumbers oph');
  }
  public function createQueryByEmailId($id)
  {
    $q = $this->createQuery();
    $a = $q->getRootAlias();
    $q->leftJoin("$a.Emails ce")
      ->leftJoin("p.Emails pe")
      ->andWhere('(TRUE')
      ->andWhere('ce.sent = TRUE')
      ->andWhere('ce.id = ?',$id)
      ->orWhere('pe.id = ?',$id)
      ->andWhere('pe.sent = TRUE')
      ->andWhere('TRUE)')
      ->orderby('name','firstname');
    return $q;
  }
  
  public function createQueryByGroupId($id)
  {
    $q = $this->createQuery();
    $a = $q->getRootAlias();
    $q->leftJoin("$a.ContactGroups gc ON $a.id = gc.contact_id AND gc.group_id = ?",$id)
      ->leftJoin("p.ProfessionalGroups gp ON p.id = gp.professional_id AND gp.group_id = ?",$id)
      ->andWhere('(gc.group_id = ? OR gp.group_id = ?)',array($id,$id))
      ->orderby('name','firstname');
    return $q;
  }
  
  public function createQuery($alias = 'a')
  {
    $p  = 'p'   != $alias ? 'p'   : 'p1';
    $pt = 'pt'  != $alias ? 'pt'  : 'pt1';
    $o  = 'o'   != $alias ? 'o'   : 'o1';
    $gp = 'gp'  != $alias ? 'gp'  : 'gp1';
    $gc = 'gc'  != $alias ? 'gc'  : 'gc1';
    $gpu = 'gpu'!= $alias ? 'gpu' : 'gpu1';
    $gcu = 'gcu'!= $alias ? 'gcu' : 'gcu1';
    $u  = 'u'   != $alias ? 'u'   : 'u1';
    $pn = 'pn'  != $alias ? 'pn'  : 'pn1';
    $y  = 'y'   != $alias ? 'y'   : 'y1';
    
    $query = parent::createQuery($alias)
      ->leftJoin("$alias.Professionals $p")
      ->leftJoin("$p.ProfessionalType $pt")
      //->leftJoin("$p.Groups $gp")
      //->leftJoin($gp.'.Picture pic'.$gp)
      //->leftJoin("$gp.User $gpu")
      ->leftJoin("$p.Organism $o")
      //->leftJoin("$alias.Groups $gc")
      //->leftJoin($gc.'.Picture pic'.$gc)
      //->leftJoin("$gc.User $gcu")
      ->leftJoin("$alias.Phonenumbers $pn")
      ->leftJoin("$alias.YOBs $y")
      ->andWhere("$alias.confirmed = ?",true);
    
    return $query;
  }

  public function findWithTickets($id)
  {
    $q = $this->createQuery('c')
      ->leftJoin("c.Transactions transac")
      ->leftJoin('transac.Payments payment')
      ->leftJoin('c.EventArchives ea')
      /*
      ->leftJoin('transac.Tickets tck ON transaction.id = tck.transaction_id AND tck.id NOT IN (SELECT tck2.cancelling FROM ticket tck2 WHERE tck2.cancelling IS NOT NULL) AND tck.duplicate IS NULL')
      ->leftJoin('tck.Manifestation manifestation')
      ->leftJoin('manifestation.Event event')
      */
      ->andWhere('c.id = ?',$id)
      ->orderBy('ea.happens_at DESC');
    $contact = $q->fetchOne();
    return $contact;
  }
  
  public function fetchOneById($id, $clear = true)
  {
    if ( ''.intval($id) !== ''.$id || intval($id) <= 0 )
      return false;
    
    return !$clear
      ? $this->createQuery('c')->andWhere('c.id = ?',$id)->orderBy('c.id')->fetchOne()
      : $this->createQuery('c')->where('c.id = ?',$id)->orderBy('c.id')->fetchOne();
  }
  
  public function doSelectOnlyGrp(Doctrine_Query $q)
  {
    $a = $q->getRootAlias();
    $q->leftJoin("p.ContactEntries ce")
      ->andWhere('ce.id IS NOT NULL');
    return $q;
  }
  
    /*
     * Returns an instance of this class.
     *
     * @return object ContactTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Contact');
    }
}
