<?php

/**
 * GeoFrDepartmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GeoFrDepartmentTable extends PluginGeoFrDepartmentTable
{
  public static function getInstance()
  {
      return Doctrine_Core::getTable('GeoFrDepartment');
  }
  
  public function fetchOneByNumCP($dpt)
  {
    return $this->createQuery('dpt')
      ->leftJoin('dpt.Region r')
      ->andWhere("REGEXP_REPLACE(dpt.num,'[a-zA-Z]','0') = ?",$dpt)
      ->fetchOne();
  }
}
