<?php

/**
 * MemberCard
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Baptiste SIMON <baptiste.simon AT e-glop.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class MemberCard extends PluginMemberCard
{
  public function __toString()
  {
    sfContext::getInstance()->getConfiguration()->loadHelpers(array('I18N','Date'));
    return __($this->name).' #'.$this->id."\n(".format_date($this->expire_at,'D').')';
  }
  
  public function postSave($event)
  {
    // prices
    $q = Doctrine::getTable('MemberCardPriceModel')->createQuery('pm')
      ->andWhere('pm.member_card_name = ?',$this->name);
    $models = $q->execute();
    
    foreach ( $models as $model )
    for ( $i = 0 ; $i < $model->quantity ; $i++ )
    {
      $mc_price = new MemberCardPrice;
      $mc_price->price_id = $model->price_id;
      $mc_price->member_card_id = $this->id;
      $mc_price->save();
    }
    
    // payments in ticketting
    $transaction = new Transaction;
    
    // member cards payment
    $payment = new Payment;
    $payment->payment_method_id = 7;
    $payment->member_card_id = $this->id;
    $payment->value = -$this->value;
    $transaction->Payments[] = $payment;
    
    // real payment
    $payment = new Payment;
    $payment->payment_method_id = 3;
    $payment->value = $this->value;
    $transaction->Payments[] = $payment;
    
    $transaction->save();
  }
}
