<?php

/**
 * OptionMandatoryFieldTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OptionMandatoryFieldTable extends PluginOptionMandatoryFieldTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object OptionMandatoryFieldTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OptionMandatoryField');
    }
}