<?php

/**
 * Organism
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Baptiste SIMON <baptiste.simon AT e-glop.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Organism extends PluginOrganism
{
  protected $module = 'organism';
  
  public function __toString()
  {
    return $this->name.($this->city ? ' ('.$this->city.')' : '');
  }
  public function toStringWithDash()
  {
    return $this->name.($this->city ? ' - '.$this->city : '');
  }
  
  public function getDepartment()
  {
    if ( trim(strtolower($this->country)) !== 'france' && $this->country || !$this->postalcode )
      return false;
    
    return Doctrine::getTable('GeoFrDepartment')->fetchOneByNumCP(substr($this->postalcode,0,2));
  }
  public function getRegion()
  {
    if ( $dpt = $this->getDepartment() )
      return $dpt->Region;
    else
      return false;
  }

  public function getGroupsPicto()
  {
    $str = '';
    foreach ( $this->Groups as $group )
    {
      if ( !sfContext::hasInstance() )
      {
        $str .= $group->getHtmlTag().' ';
        continue;
      }

      $sf_user = sfContext::getInstance()->getUser();
      $users = array();
      foreach ( $group->Users as $user )
        $users[] = $user->id;
      if ( $group->sf_guard_user_id == $sf_user->getId()
        || is_null($group->sf_guard_user_id) && (in_array($sf_user->getId(), $users) || $sf_user->hasCredential(array('admin','super-admin'),false)) )
        $str .= $group->getHtmlTag().' ';
    }
    return $str;
  }
}
