<?php

/**
 * PhoneType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PhoneType extends PluginPhoneType
{
  public function preSave($event)
  {
    $this->type = 'phone';
    parent::preSave($event);
  }
}
