<?php

/**
 * PhoneTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PhoneTypeTable extends PluginPhoneTypeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PhoneTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PhoneType');
    }
}