<?php

/**
 * Professional
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Baptiste SIMON <baptiste.simon AT e-glop.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Professional extends PluginProfessional
{
  public function __toString()
  {
    sfApplicationConfiguration::getActive()->loadHelpers(array('I18N'));
    return ($this->name ? $this->name : $this->ProfessionalType ? $this->ProfessionalType : $this->Contact).' '.__('at',array(),'contact').' '.$this->Organism;
  }
  public function getFullName()
  {
    sfApplicationConfiguration::getActive()->loadHelpers(array('I18N'));
    return $this->Contact.', '.($this->name ? $this->name : $this->ProfessionalType).' '.__('at').' '.$this->Organism;
  }
  public function getNameType()
  {
    return $this->name ? $this->name.($this->ProfessionalType ? ' ('.$this->ProfessionalType.')' : '') : $this->ProfessionalType;
  }
  public function getFullDesc()
  {
    return $this->Organism.' ('.($this->name ? $this->name : $this->ProfessionalType).')';
  }
  public function getEvents()
  {
    if ( isset($this->events) )
      return $this->events;
      
    return $this->events = Doctrine_Query::create()->from('Event e')
      ->leftJoin('e.Manifestations m')
      ->leftJoin('m.Tickets tck')
      ->leftJoin('tck.Transaction t')
      ->andWhere('professional_id = ?',$this->id)
      ->select('e.*') 
      ->execute();
  }
  
  public function getGroupsPicto()
  {
    $str = '';
    foreach ( $this->Groups as $group )
      $str .= $group->getHtmlTag().' ';
    return $str;
  }
}
