<?php

/**
 * ProfessionalArchiveTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfessionalArchiveTable extends PluginProfessionalArchiveTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfessionalArchiveTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProfessionalArchive');
    }
}