<?php

/**
 * TitleTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TitleTypeTable extends PluginTitleTypeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object TitleTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TitleType');
    }
    
    public function fetchOneById($id)
    {
      return $this->createQuery('q')->andWhere('q.id = ?',$id)->fetchOne();
    }
}
