<?php

/**
 * TypeOfResourcesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TypeOfResourcesTable extends PluginTypeOfResourcesTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object TypeOfResourcesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TypeOfResources');
    }
}