<?php

/**
 * YOB
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Baptiste SIMON <baptiste.simon AT e-glop.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class YOB extends PluginYOB
{
  protected function getWithPadding($field, $pad = 2)
  {
    return $this->rawGet($field) ? str_pad($this->rawGet($field), $pad, '0', STR_PAD_LEFT) : '';
  }
  public function getDay()
  {
    return $this->getWithPadding('day');
  }
  public function getMonth()
  {
    return $this->getWithPadding('month');
  }
  public function getYear()
  {
    return $this->getWithPadding('year',4);
  }
  
  public function __toString()
  {
    sfApplicationConfiguration::getActive()->loadHelpers(array('Date'));
    
    if ( $this->day && $this->month )
      $r = format_date($this->year.'-'.$this->month.'-'.$this->day);
    else
      $r = $this->year;
     
     $r .= ' ';
     $r .= $this->name ? $this->name : '';
     
     return $r;
  }
}
