<?php

/**
 * YOB
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Baptiste SIMON <baptiste.simon AT e-glop.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class YOB extends PluginYOB
{
  function __toString()
  {
    sfApplicationConfiguration::getActive()->loadHelpers(array('Date'));
    
    if ( $this->day && $this->month )
      $r = format_date($this->year.'-'.$this->month.'-'.$this->day);
    else
      $r = $this->year;
     
     $r .= $this->name ? $this->name : '';
     
     return $r;
  }
}
