<?php

/**
 * PluginBoughtProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginBoughtProductTable extends TraceableTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginBoughtProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginBoughtProduct');
    }
}