<?php

/**
 * PluginProductWorkspaceLinkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginProductWorkspaceLinkTable extends ProductLinkTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginProductWorkspaceLinkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginProductWorkspaceLink');
    }
}