<?php

/**
 * PluginProductDeclinationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginProductDeclinationTable extends TraceableTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginProductDeclinationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginProductDeclination');
    }
}