<?php

/**
 * PluginProductProductLinkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginProductProductLinkTable extends ProductLinkTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginProductProductLinkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginProductProductLink');
    }
}