<?php

/**
 * PluginProductMetaEventLinkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginProductMetaEventLinkTable extends ProductLinkTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginProductMetaEventLinkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginProductMetaEventLink');
    }
}