<?php

/**
 * PluginProductPriceLinkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginProductPriceLinkTable extends ProductLinkTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginProductPriceLinkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginProductPriceLink');
    }
}