<?php

/**
 * EntryElementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EntryElementTable extends PluginEntryElementTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object EntryElementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EntryElement');
    }
    
    public function fetchOneByContactManifestation($contact_id, $manifestation_id)
    {
      $q = $this->createQuery('ee')
        ->andWhere('ee.contact_entry_id = ?',$contact_id)
        ->andWhere('ee.manifestation_entry_id = ?',$manifestation_id)
        ->orderBy('id');
      return $q->fetchOne();
    }
}
