<?php

/**
 * GroupWorkspaceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GroupWorkspaceTable extends PluginGroupWorkspaceTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object GroupWorkspaceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GroupWorkspace');
    }
}