<?php

/**
 * ManifestationEntryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ManifestationEntryTable extends PluginManifestationEntryTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ManifestationEntryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ManifestationEntry');
    }
}