<?php

/**
 * GroupDeletedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GroupDeletedTable extends PluginGroupDeletedTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object GroupDeletedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GroupDeleted');
    }
}