<?php

/**
 * GroupAutoUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GroupAutoUserTable extends PluginGroupAutoUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object GroupAutoUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GroupAutoUser');
    }
}