<?php

/**
 * GroupOrganismTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GroupOrganismTable extends PluginGroupOrganismTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object GroupOrganismTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GroupOrganism');
    }
}