<?php

/**
 * GroupContactTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GroupContactTable extends PluginGroupContactTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object GroupContactTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GroupContact');
    }
}