<?php

/**
 * Group
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Baptiste SIMON <baptiste.simon AT e-glop.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Group extends PluginGroup
{
  public function __toString()
  {
    if ( !$this->User || !$this->User->id )
      return parent::__toString();
    else
      return '('.$this->User->username.') '.parent::__toString();
  }
}
