<?php

/**
 * GroupUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GroupUserTable extends PluginGroupUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object GroupUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GroupUser');
    }
}