<?php

/**
 * PluginEmailActionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginEmailActionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginEmailActionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginEmailAction');
    }
}