<?php

/**
 * PluginEmailTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginEmailTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginEmailTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginEmail');
    }
    
    public function __constructor(string $name, Doctrine_Connection $conn, boolean $initDefinition)
    {
      parent::__constructor($name,$conn,$initDefinition);
      $this->getTemplate('Doctrine_Template_Searchable')->getPlugin()
        ->setOption('analyzer', new MySearchAnalyzer());
    }
}
