<?php

/**
 * PluginEmailExternalLinkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginEmailExternalLinkTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginEmailExternalLinkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginEmailExternalLink');
    }
}