<?php

/**
 * PluginEmailLinkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginEmailLinkTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginEmailLinkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginEmailLink');
    }
}