<?php

/**
 * PluginEmailOrganismTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginEmailOrganismTable extends EmailLinkTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginEmailOrganismTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginEmailOrganism');
    }
}