<?php

/**
 * PluginEmailSpoolTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginEmailSpoolTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginEmailSpoolTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginEmailSpool');
    }
}