<?php

/**
 * PluginEmailProfessionalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginEmailProfessionalTable extends EmailLinkTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginEmailProfessionalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginEmailProfessional');
    }
}