<?php

/**
 * PluginEmailContactTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginEmailContactTable extends EmailLinkTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginEmailContactTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginEmailContact');
    }
}