<?php

/**
 * PluginGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginGroup');
    }
}