<?php

/**
 * PluginGroupOrganismTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginGroupOrganismTable extends GroupDetailTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginGroupOrganismTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginGroupOrganism');
    }
}