<?php

/**
 * PluginGroupDeletedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginGroupDeletedTable extends GroupDetailTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginGroupDeletedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginGroupDeleted');
    }
}