<?php

/**
 * PluginGroupDetailTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginGroupDetailTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginGroupDetailTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginGroupDetail');
    }
}