<?php

/**
 * PluginGroupUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginGroupUserTable extends GroupDetailTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginGroupUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginGroupUser');
    }
}