<?php

/**
 * PluginGroupAutoUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginGroupAutoUserTable extends GroupDetailTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginGroupAutoUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginGroupAutoUser');
    }
}