<?php

/**
 * AddressableTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddressableTable extends PluginAddressableTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object AddressableTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Addressable');
    }
}