<?php

/**
 * DomainTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DomainTable extends PluginDomainTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object DomainTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Domain');
    }
}