<?php

/**
 * FilterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FilterTable extends PluginFilterTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object FilterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Filter');
    }
}