<?php

/**
 * ItemableTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ItemableTable extends PluginItemableTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ItemableTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Itemable');
    }
}