<?php

/**
 * JabberTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JabberTable extends PluginJabberTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object JabberTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Jabber');
    }
}