<?php

/**
 * OptionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OptionTable extends PluginOptionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object OptionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Option');
    }
}