<?php

/**
 * Picture
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Baptiste SIMON <baptiste.simon AT e-glop.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Picture extends PluginPicture
{
  public function getImageTag($inline = false)
  {
    if ( !$inline )
      return '<img src="data:'.$this->type.';base64,'.$this->content.'" alt="'.$this->name.'" />';
    else
    {
      sfApplicationConfiguration::getActive()->loadHelpers(array('CrossAppLink'));
      return '<img src="'.cross_app_url_for('default', 'picture/display?id='.$this->id).'" alt="'.$this->name.'" />';
    }
  }
  
  public function getContentStream()
  {
    return $this->rawGet('content');
  }
  public function getDecodedContent()
  {
    return base64_decode($this->getContent());
  }
  public function getContent()
  {
    if ( !is_resource($this->rawGet('content')) )
      return $this->rawGet('content');
    
    return stream_get_contents($this->rawGet('content'));
  }
}
