<?php

/**
 * PluginMemberCardTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginMemberCardTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginMemberCardTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginMemberCardType');
    }
}