<?php

/**
 * PluginMemberCardTypePromoCodeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginMemberCardTypePromoCodeTable extends TraceableTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginMemberCardTypePromoCodeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginMemberCardTypePromoCode');
    }
}