<?php

/**
 * PluginMemberCardTypeUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginMemberCardTypeUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginMemberCardTypeUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginMemberCardTypeUser');
    }
}