<?php

/**
 * PluginMemberCardPriceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginMemberCardPriceTable extends TraceableTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginMemberCardPriceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginMemberCardPrice');
    }
}