<?php

/**
 * PluginPicture
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Baptiste SIMON <baptiste.simon AT e-glop.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginPicture extends BasePicture
{
  protected function resize()
  {
    if ( $this->width && $this->height )
    try {
      $resizer = new Imagick;
      if ( !$resizer->readImageBlob($this->getDecodedContent()) )
        throw new liEvenementException('A problem occurred during Image reading');
      $resizer->resizeImage($this->width, $this->height, Imagick::FILTER_LANCZOS, 1);
      $this->content = base64_encode($resizer->getImageBlob());
    }
    catch ( Exception $e ) {}
  }
  public function preSave($event)
  {
    $this->resize();
    parent::preSave($event);
  }
}
