<?php

/**
 * PluginAuthenticationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginAuthenticationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginAuthenticationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginAuthentication');
    }
}