<?php

/**
 * PluginFilterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginFilterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginFilterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginFilter');
    }
}