<?php

/**
 * PluginDomainTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDomainTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDomainTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDomain');
    }
}