<?php

/**
 * PluginPostalcodeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPostalcodeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPostalcodeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPostalcode');
    }
}