<?php

/**
 * PluginJabberTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginJabberTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginJabberTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginJabber');
    }
}