<?php

/**
 * PluginTraceableTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTraceableTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTraceableTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTraceable');
    }
}