<?php

/**
 * PluginOptionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginOptionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginOptionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginOption');
    }
}