<?php

/**
 * PluginCacheTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCacheTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginCacheTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginCache');
    }
}