<?php

/**
 * PluginModelTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginModelTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginModelTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginModelType');
    }
}