<?php

/**
 * PluginPictureTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPictureTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPictureTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPicture');
    }
}