<?php

/**
 * sfGuardUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Baptiste SIMON <baptiste.simon AT e-glop.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUser extends PluginsfGuardUser
{
  public function save(Doctrine_Connection $conn = null)
  {
    if ( $this->email_address && $this->username )
      parent::save($conn);
  }
  
  public function preSave($event)
  {
    parent::preSave($event);
    
    // clear cache
    Doctrine::getTable('Cache')->createQuery('c')
      ->andWhere('c.domain = ?', 'rp-index')
      ->andWhere('c.identifier LIKE ?', '%sf_guard_user_id='.$this->id)
      ->delete()
      ->execute();
  }
  
  public function __toString()
  {
    return (string) $this->getUsername().' ('.$this->getName().')';
  }
}
