<?php

/**
 * sfGuardGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Baptiste SIMON <baptiste.simon AT e-glop.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardGroup extends PluginsfGuardGroup
{
  public function getNameWithDescription()
  {
    sfApplicationConfiguration::getActive()->loadHelpers(array('I18N'));
    if ( sfConfig::get('app_sf_guard_display_group_description',false) )
      return $this->name.' ('.__($this->description,null,'sf_guard').')';
    else
      return (string)$this;
  }
}
