<?php

/**
 * PricePOSTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PricePOSTable extends PluginPricePOSTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PricePOSTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PricePOS');
    }
}