<?php

/**
 * Price
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Baptiste SIMON <baptiste.simon AT e-glop.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Price extends PluginPrice
{
  public function getFullName()
  {
    sfApplicationConfiguration::getActive()->loadHelpers(array('Number'));
    return $this->description.' ('.$this->name.'), '.format_currency($this->value,'€');
  }
  
  public function getWorkspaceIds()
  {
    $arr = array();
    foreach ( $this->Workspaces as $ws )
      $arr[] = $ws->id;
    return $arr;
  }
  
  public function isAccessibleBy(sfSecurityUser $user, $option = NULL)
  {
    return in_array($user->getId(), $this->Users->getPrimaryKeys());
  }
}
