<?php

/**
 * PriceManifestationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PriceManifestationTable extends PluginPriceManifestationTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PriceManifestationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PriceManifestation');
    }
  
  /*
  public function createQuery($alias = 'pm')
  {
    $p = $alias != 'p' ? 'p' : 'p1';
    $m = $alias != 'm' ? 'm' : 'm1';
    
    $q = parent::createQuery($alias)
      ->leftJoin("$alias.Price $p")
      ->leftJoin("$alias.Manifestation $m");
    
    return $q;
  }
  */
}
