<?php

/**
 * PriceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PriceTable extends PluginPriceTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PriceTable
     */
    public static function getInstance()
    {
      return Doctrine_Core::getTable('Price');
    }
    
    public function createQuery($alias = 'p')
    {
      $q = parent::createQuery($alias);
      
      if ( sfContext::hasInstance() )
      {
        $user = sfContext::getInstance()->getUser();
        if ( !$user->isSuperAdmin() && !$user->hasCredential('event-admin-price') )
          $q->andWhere("$alias.id IN (SELECT up.price_id FROM UserPrice up WHERE up.sf_guard_user_id = ?) OR (SELECT count(up2.price_id) FROM UserPrice up2 WHERE up2.sf_guard_user_id = ?) = 0",array($user->getId(),$user->getId()));
      }
      
      return $q;
    }
    
    public function fetchOneByName($name)
    {
      $q = $this->createQuery('p')->andWhere('name = ?',$name);
      return $q->fetchOne();
    }
}
