<?php

/**
 * PriceGaugeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PriceGaugeTable extends PluginPriceGaugeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PriceGaugeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PriceGauge');
    }
}