<?php

/**
 * PriceManifestation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Baptiste SIMON <baptiste.simon AT e-glop.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PriceManifestation extends PluginPriceManifestation
{
  public static function createPrice(Price $price)
  {
    $pm = new PriceManifestation();
    $pm->price_id = $price->id;
    $pm->value = $price->value;
    return $pm;
  }
  
  public function preSave($event)
  {
    if ( is_null($this->value) )
      $this->value = $this->Price->value;
    parent::preSave($event);
  }
  
  public function getFullName()
  {
    sfApplicationConfiguration::getActive()->loadHelpers(array('Number'));
    return $this->Price->name.' ('.$this->Price->description.'), '.format_currency($this->value,'€');
  }
}
