<?php

/**
 * PriceProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PriceProductTable extends PluginPriceProductTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PriceProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PriceProduct');
    }
}