<?php

/**
 * PricePOSTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PricePOSTable extends PluginPricePOSTable
{
  public function retrieveList()
  {
    return $this->createQuery('pos')
      ->leftJoin('pos.Price p');
  }
  
  /**
   * Returns an instance of this class.
   *
   * @return object PricePOSTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PricePOS');
  }
}
