<?php

/**
 * WorkspacePriceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WorkspacePriceTable extends PluginWorkspacePriceTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WorkspacePriceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WorkspacePrice');
    }
}