<?php

/**
 * PluginEntryTicketsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginEntryTicketsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginEntryTicketsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginEntryTickets');
    }
}