<?php

/**
 * PluginManifestationEntryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginManifestationEntryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginManifestationEntryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginManifestationEntry');
    }
}