<td class="sos-st-og"><span class="money">-</span><span class="percent">-</span></td>
<td class="f-st-og"><span class="nb">-</span><span class="percent">-</span></td>
<td class="sos-st-sg"><span class="money">-</span><span class="percent">-</span></td>
<td class="f-st-sg"><span class="nb">-</span><span class="percent">-</span></td>
<td class="sos-st-ag"><span class="money">-</span><span class="percent">-</span></td>
<td class="f-st-ag"><span class="nb">-</span><span class="percent">-</span></td>
<td class="sos-at-og"><span class="money">-</span><span class="percent">-</span></td>
<td class="f-at-og"><span class="nb">-</span><span class="percent">-</span></td>
<td class="sos-at-sg"><span class="money">-</span><span class="percent">-</span></td>
<td class="f-at-sg"><span class="nb">-</span><span class="percent">-</span></td>
<td class="sos-at-ag"><span class="money">-</span><span class="percent">-</span></td>
<td class="f-at-ag"><span class="nb">-</span><span class="percent">-</span></td>
