<?php

/**
 * EventCompanyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventCompanyTable extends PluginEventCompanyTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object EventCompanyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EventCompany');
    }
}