<?php

/**
 * EventCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventCategoryTable extends PluginEventCategoryTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object EventCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EventCategory');
    }
}