<?php

/**
 * EventTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventTable extends PluginEventTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object EventTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Event');
    }

  public function createQuery($alias = 'a')
  {
    $me  = 'me'   != $alias ? 'me'   : 'me1';
    $ec  = 'ec'   != $alias ? 'ec'   : 'ec1';
    
    return parent::createQuery($alias)
      ->leftJoin("$alias.MetaEvent $me")
      ->leftJoin("$alias.EventCategory $ec")
    ;
  }
}
