<?php

/**
 * GaugeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GaugeTable extends PluginGaugeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object GaugeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Gauge');
    }
  
  public function createQuery($alias = 'g')
  {
    $ws = $alias != 'ws' ? 'ws' : 'ws1';
    
    return parent::createQuery($alias)
      ->andWhere('(TRUE')
      ->andWhere("$alias.manifestation_id IS NULL")
      ->orWhereIn("$alias.workspace_id",array_keys(sfContext::getInstance()->getUser()->getWorkspacesCredentials()))
      ->andWhere('TRUE)');
  }
}
