<?php

/**
 * LocationBookingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LocationBookingTable extends PluginLocationBookingTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object LocationBookingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LocationBooking');
    }
}