<?php

/**
 * LocationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LocationTable extends PluginLocationTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object LocationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Location');
    }

  public function createQuery($alias = 'a')
  {
    $o  = 'o'   != $alias ? 'o'   : 'o1';
    $c  = 'c'   != $alias ? 'c'   : 'c1';
        
    return parent::createQuery($alias)
      ->leftJoin("$alias.Organism $o")
      ->leftJoin("$alias.Contact $c")
    ;
  }
}
