<?php

/**
 * ManifestationOrganizerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ManifestationOrganizerTable extends PluginManifestationOrganizerTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ManifestationOrganizerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ManifestationOrganizer');
    }
}