<?php

/**
 * ManifestationContactTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ManifestationContactTable extends PluginManifestationContactTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ManifestationContactTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ManifestationContact');
    }
}