<?php

/**
 * ManifestationExtraInformationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ManifestationExtraInformationTable extends PluginManifestationExtraInformationTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ManifestationExtraInformationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ManifestationExtraInformation');
    }
}