<?php

/**
 * MetaEventTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MetaEventTable extends PluginMetaEventTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object MetaEventTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MetaEvent');
    }
}