<?php

/**
 * MetaEventUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MetaEventUserTable extends PluginMetaEventUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object MetaEventUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MetaEventUser');
    }
}