<?php

/**
 * SeatingPlanTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SeatingPlanTable extends PluginSeatingPlanTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object SeatingPlanTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SeatingPlan');
    }
}