<?php

/**
 * SeatTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SeatTable extends PluginSeatTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object SeatTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Seat');
    }
}