<?php

/**
 * SeatedPlanWorkspaceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SeatedPlanWorkspaceTable extends PluginSeatedPlanWorkspaceTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object SeatedPlanWorkspaceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SeatedPlanWorkspace');
    }
}