<?php

/**
 * VatTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VatTable extends PluginVatTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object VatTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Vat');
    }
}