<?php

/**
 * WorkspaceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WorkspaceTable extends PluginWorkspaceTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WorkspaceTable
     */
    public static function getInstance()
    {
      return Doctrine_Core::getTable('Workspace');
    }
  
  public function createQuery($alias = 'w',$full = false)
  {
    $q = parent::createQuery($alias);
    if ( sfContext::hasInstance('default') )
    if ( !$full && !sfContext::getInstance()->getUser()->getGuardUser()->getIsSuperAdmin() && !sfContext::getInstance()->getUser()->hasCredential('event-admin-workspace') )
      $q->andWhereIn("$alias.id",array_keys(sfContext::getInstance()->getUser()->getWorkspacesCredentials()));
    return $q;
  }
}
