<?php

/**
 * Workspace
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Baptiste SIMON <baptiste.simon AT e-glop.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Workspace extends PluginWorkspace
{
  public function getNameForTicket()
  {
    return $this->on_ticket ? $this->on_ticket : $this->name;
  }
  
  // hack to be able to unlink manifesations from a workspace
  public function unlinkInDb($alias, $ids = array())
  {
    $rel = $this->getTable()->getRelation($alias);
    if ( $rel->getAssociationTable()->getTableName() == 'gauge' && $rel instanceof Doctrine_Relation_Association)
    {
      $q = $rel->getAssociationTable()
        ->createQuery('g',false)
        ->delete()
        ->where($rel->getLocal() . ' = ?', array_values($this->identifier()));
      
      if (count($ids) > 0) {
        $q->whereIn($rel->getForeign(), $ids);
      }
      
      $q->execute();
      return $this;
    }
    else
      return parent::unlinkInDb($alias, $ids);
  }
}
