<?php

/**
 * WorkspaceUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WorkspaceUserTable extends PluginWorkspaceUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WorkspaceUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WorkspaceUser');
    }
}