<?php

/**
 * WorkspaceUserOrderingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WorkspaceUserOrderingTable extends PluginWorkspaceUserOrderingTable
{
  public function createQuery($alias = 'wuo')
  {
    return parent::createQuery($alias)
      ->andWhere("$alias.sf_guard_user_id = ?",sfContext::hasInstance() ? sfContext::getInstance()->getUser()->getId() : 0)
      ->leftJoin("$alias.Workspace w")
      ->leftJoin('w.Users u')
      ->andWhere('u.id = ?',sfContext::hasInstance() ? sfContext::getInstance()->getUser()->getId() : 0);
  }
  
    /**
     * Returns an instance of this class.
     *
     * @return object WorkspaceUserOrderingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WorkspaceUserOrdering');
    }
}
