<?php

/**
 * PluginFailedControlTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginFailedControlTable extends TraceableTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginFailedControlTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginFailedControl');
    }
}