<?php

/**
 * PluginCheckTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCheckTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginCheckTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginCheck');
    }
}