<?php

/**
 * PluginCheckpointTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCheckpointTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginCheckpointTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginCheckpoint');
    }
}