<?php

/**
 * Attachment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Baptiste SIMON <baptiste.simon AT e-glop.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Attachment extends PluginAttachment
{
  public function __toString()
  {
    return $this->original_name.' ('.$this->mime_type.')';
  }
  
  public function getWebUri()
  {
    $up  = sfConfig::get('sf_upload_dir');
    return '/'.basename($up).'/'.$this->filename;
  }
}
