<?php

/**
 * EmailSpoolTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EmailSpoolTable extends PluginEmailSpoolTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object EmailSpoolTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EmailSpool');
    }

  public function getSpooledMessages()
  {
    return $this->createQuery('m')
      ->orderBy('m.priority')
    ;
  }
}
