<?php

/**
 * EmailExternalLinkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EmailExternalLinkTable extends PluginEmailExternalLinkTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object EmailExternalLinkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EmailExternalLink');
    }
}