<?php

/**
 * EmailProfessionalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EmailProfessionalTable extends PluginEmailProfessionalTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object EmailProfessionalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EmailProfessional');
    }
}