<?php

/**
 * EmailLinkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EmailLinkTable extends PluginEmailLinkTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object EmailLinkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EmailLink');
    }
}