<?php

/**
 * EmailOrganismTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EmailOrganismTable extends PluginEmailOrganismTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object EmailOrganismTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EmailOrganism');
    }
}