<?php

/**
 * EmailContactTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EmailContactTable extends PluginEmailContactTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object EmailContactTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EmailContact');
    }
}