<?php

/**
 * EmailActionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EmailActionTable extends PluginEmailActionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object EmailActionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EmailAction');
    }
}