<?php
  // generated by modules/*/config/tdp.yml, the "actions" properties
  
  $i = 0;
  $last = false;
  foreach ( $config->getRaw('actions') as $name => $action )
  {
    $i++;
    
    // attributes
    if ( !isset($action['attributes']) )
      $action['attributes'] = array();
    if ( !isset($action['attributes']['class']) )
      $action['attributes']['class'] = 'action';
    else
      $action['attributes']['class'] .= ' action';
    
    if ( $i == 3 )
    {
      $action['attributes']['class'] .= ' group';
      $last = array('name' => $name, 'action' => $action);
      continue;
    }
    
    if ( $i == 4 )
      echo '<div class="tdp-submenu">';
    
    echo !(isset($action['credential']) && !$sf_user->hasCredential($action['credential']))
      ? link_to(isset($action['label']) ? __($action['label']) : __(ucfirst(strpos($name,'batch') === 0 ? substr($name,5) : $name),null,'sf_admin'),$sf_context->getModuleName().'/'.(strpos($name,'batch') === 0 ? 'batch?batch_action='.$name : $name.(isset($object) && isset($action['with_id'])? '?id='.$object->id : '')),$action['attributes'])
      : '<a href="#">'.(isset($action['label']) ? __($action['label']) : __(ucfirst(strpos($name,'batch') === 0 ? substr($name,5) : $name),null,'sf_admin')).'</a>';
  }
  
  if ( $i > 3 )
    echo '</div>';
  if ( $last )
  {
    echo !(isset($last['action']['credential']) && !$sf_user->hasCredential($last['action']['credential']))
      ? link_to(isset($last['action']['label']) ? __($last['action']['label']) : __(ucfirst(strpos($last['name'],'batch') === 0 ? substr($last['name'],5) : $last['name']),null,'sf_admin'),$sf_context->getModuleName().'/'.(strpos($last['name'],'batch') === 0 ? 'batch?batch_action='.$last['name'] : $last['name'].(isset($object) && isset($action['with_id'])? '?id='.$object->id : '')),$last['action']['attributes'])
      : '<a href="#" class="'.$last['action']['attributes']['class'].'">'.(isset($last['action']['label']) ? __($last['action']['label']) : __(ucfirst(strpos($last['name'],'batch') === 0 ? substr($last['name'],5) : $last['name']),null,'sf_admin')).'</a>';
  }
?>
