<?php

/**
 * BoughtProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BoughtProductTable extends PluginBoughtProductTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object BoughtProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BoughtProduct');
    }
}