<?php

/**
 * ProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductTable extends PluginProductTable
{
  public function createQuery($alias = 'p')
  {
    return parent::createQuery($alias)
      ->leftJoin("$alias.Translation pt")
      ->leftJoin("$alias.Declinations d")
      ->leftJoin('d.Translation dt')
    ;
  }
  
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Product');
  }
  
  public function retrievePublicList()
  {
    $q = $this->createQuery('p')
      ->leftJoin('p.Category c')
      ->leftJoin('c.Translation ct')
      ->andWhere('c.online = ?', true)
      ->leftJoin('p.Prices price')
      ->andWhere('price.online = ?', true)
      ->leftJoin('price.Users u')
    ;
    if ( sfContext::hasInstance() )
      $q->andWhere('u.id = ?', sfContext::getInstance()->getUser()->getId());
    return $q;
  }
}
