<?php

/**
 * ProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductTable extends PluginProductTable
{
  public function createQuery($alias = 'p')
  {
    return parent::createQuery($alias)
      ->leftJoin("$alias.Translation pt");
  }
  
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Product');
  }
}
