<?php

/**
 * ProductManifestationLinkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductManifestationLinkTable extends PluginProductManifestationLinkTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductManifestationLinkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductManifestationLink');
    }
}