<?php

/**
 * ProductMetaEventLinkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductMetaEventLinkTable extends PluginProductMetaEventLinkTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductMetaEventLinkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductMetaEventLink');
    }
}