<?php

/**
 * ProductPriceLinkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductPriceLinkTable extends PluginProductPriceLinkTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductPriceLinkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductPriceLink');
    }
}