<?php

/**
 * Product
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Baptiste SIMON <baptiste.simon AT e-glop.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Product extends PluginProduct implements liUserAccessInterface
{
  public function setUp()
  {
    parent::setUp();
    $this->_table->getTemplate('Doctrine_Template_Searchable')
      ->getPlugin()
      ->setOption('analyzer',new MySearchAnalyzer());
  }
  
  public function isAccessibleBy(sfSecurityUser $user, $option = NULL)
  {
    // meta event
    if ( $this->meta_event_id && !in_array($this->meta_event_id, array_keys($user->getMetaEventsCredentials())) )
      return false;
    
    // prices
    if ( $this->Prices->count() == 0 )
      return false;
    foreach ( $this->Prices as $price )
    if ( !in_array($user->getId(), $price->Users->getPrimaryKeys()) )
      return false;
    
    return true;
  }
}
