<?php

/**
 * ProductCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductCategoryTable extends PluginProductCategoryTable
{
  public function createQuery($alias = 'pc')
  {
    return parent::createQuery($alias)
      ->leftJoin("$alias.Translation pct");
  }
  public static function getInstance()
  {
    return Doctrine_Core::getTable('ProductCategory');
  }
}
