<?php
/**********************************************************************************
*
*	    This file is part of e-venement.
*
*    e-venement is free software; you can redistribute it and/or modify
*    it under the terms of the GNU General Public License as published by
*    the Free Software Foundation; either version 2 of the License.
*
*    e-venement is distributed in the hope that it will be useful,
*    but WITHOUT ANY WARRANTY; without even the implied warranty of
*    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*    GNU General Public License for more details.
*
*    You should have received a copy of the GNU General Public License
*    along with e-venement; if not, write to the Free Software
*    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
*
*    Copyright (c) 2006-2016 Baptiste SIMON <baptiste.simon AT e-glop.net>
*    Copyright (c) 2006-2016 Libre Informatique [http://www.libre-informatique.fr/]
*
***********************************************************************************/
?>
<?php
class RemoveLockFilesTask extends sfBaseTask{

  protected function configure() {
    $this->addArguments(array(
      new sfCommandArgument('go', sfCommandArgument::OPTIONAL, 'Whether we try or we executes the clearance'),
      new sfCommandArgument('application', sfCommandArgument::OPTIONAL, '', 'event'),
    ));
    $this->addOptions(array(
      new sfCommandOption('env', null, sfCommandOption::PARAMETER_REQUIRED, 'The environment', 'dev'),
    ));
    $this->namespace = 'e-venement';
    $this->name = 'remove-lock-files';
    $this->briefDescription = 'Removes lock files';
    $this->detailedDescription = <<<EOF
      The [rlf:remove-lock-files|INFO] removes the lock files generated by the garbage collectors when caching data
      [./symfony e-venement:remove-lock-files --env=dev [application]|INFO]
EOF;
  }

  protected function execute($arguments = array(), $options = array())
  {
    sfContext::createInstance($this->configuration, $options['env']);
    $databaseManager = new sfDatabaseManager($this->configuration);
    $this->logSection('LockFiles', 'Clearing lock files for application '.$arguments['application'].' and environment '.$options['env']);
    
    if ( file_exists($path = sfConfig::get('sf_app_cache_dir').'/caching_manifestations.lock') )
    {
      unlink($path);
      $this->logSection('LockFile', 'A file found and removed');
    }
    else
      $this->logSection('LockFile', 'No file found');
  }
}
