<?php

/**
 * RemoteAuthenticationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RemoteAuthenticationTable extends PluginRemoteAuthenticationTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object RemoteAuthenticationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RemoteAuthentication');
    }
}