<?php

/**
 * SurveyApplyToTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SurveyApplyToTable extends PluginSurveyApplyToTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object SurveyApplyToTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SurveyApplyTo');
    }
}