<?php

/**
 * SurveyQueryOptionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SurveyQueryOptionTable extends PluginSurveyQueryOptionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object SurveyQueryOptionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SurveyQueryOption');
    }
}