<?php

/**
 * SurveyAnswersGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SurveyAnswersGroupTable extends PluginSurveyAnswersGroupTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object SurveyAnswersGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SurveyAnswersGroup');
    }
}