<?php

/**
 * SurveyOptionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SurveyOptionsTable extends PluginSurveyOptionsTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object SurveyOptionsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SurveyOptions');
    }
}