<?php

/**
 * WebOriginTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WebOriginTable extends PluginWebOriginTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WebOriginTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WebOrigin');
    }
}