<?php

/**
 * WebOriginTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WebOriginTable extends PluginWebOriginTable
{
  public function retrieveList()
  {
    return $this->createQuery('wo')
      ->leftJoin('wo.User')
      ->leftJoin('wo.Transaction t')
      ->leftJoin('t.Order o')
      ->leftJoin('t.Payments p')
    ;
  }
  
  public static function getInstance()
  {
    return Doctrine_Core::getTable('WebOrigin');
  }
}
