<?php

/**
 * CheckTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CheckTable extends PluginCheckTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object CheckTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Check');
    }
}