<?php

/**
 * FailedControlTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FailedControlTable extends PluginFailedControlTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object FailedControlTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FailedControl');
    }
}