<?php

/**
 * FailedControl
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Baptiste SIMON <baptiste.simon AT e-glop.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class FailedControl extends PluginFailedControl
{
  public function complete(Array $params)
  {
    foreach ( array('checkpoint_id', 'comment', 'ticket_id') as $field )
    if ( isset($params[$field]) )
      $this->$field = is_array($params[$field]) ? implode(', ', $params[$field]) : $params[$field];
    return $this->save();
  }
}
