<?php

/**
 * PluginWorkspaceUserOrderingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWorkspaceUserOrderingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWorkspaceUserOrderingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWorkspaceUserOrdering');
    }
}