<?php

/**
 * PluginManifestationOrganizerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginManifestationOrganizerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginManifestationOrganizerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginManifestationOrganizer');
    }
}