<?php

/**
 * PluginManifestationContactTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginManifestationContactTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginManifestationContactTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginManifestationContact');
    }
}