<?php

/**
 * PluginManifestation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Baptiste SIMON <baptiste.simon AT e-glop.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginManifestation extends BaseManifestation implements liEventSecurityAccessor
{
  public function preSave($event)
  {
    $this->duration = intval($this->rawGet('duration')).'' == ''.$this->rawGet('duration')
      ? $this->rawGet('duration')
      : intval(strtotime($this->rawGet('duration').'+0',0));
    parent::preSave($event);
  }
  public function getDuration()
  {
    $duration = $this->rawGet('duration');
    if ( intval($this->rawGet('duration')).'' != ''.$this->rawGet('duration') )
      return $duration;
    
    $hours = floor($duration/3600);
    $minutes = floor($duration%3600/60) > 9 ? floor($duration%3600/60) : '0'.floor($duration%3600/60);
    return $hours.':'.$minutes;
  }
  
  public function getMEid()
  {
    return $this->Event->getMEid();
  }
}
