<?php

/**
 * PluginManifestationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginManifestationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginManifestationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginManifestation');
    }
}