<?php

/**
 * PluginLocationBookingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginLocationBookingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginLocationBookingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginLocationBooking');
    }
}