<?php

/**
 * PluginEvent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Baptiste SIMON <baptiste.simon AT e-glop.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginEvent extends BaseEvent implements liMetaEventSecurityAccessor
{
  public function preSave($event)
  {
    $this->duration = intval($this->duration).'' == ''.$this->duration
      ? $this->duration
      : intval(strtotime(date('Y-m-d',0).' '.$this->duration.'+0'));
    parent::preSave($event);
  }
  public function getDurationHR()
  {
    if ( intval($this->duration).'' != ''.$this->duration )
      return $this->duration;
    
    $hours = floor($this->duration/3600);
    $minutes = floor($this->duration%3600/60) > 9 ? floor($this->duration%3600/60) : '0'.floor($this->duration%3600/60);
    return $hours.':'.$minutes;
  }
  
  public function getMEid()
  {
    return $this->meta_event_id;
  }
}
