<?php

/**
 * PluginSeatLinkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSeatLinkTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSeatLinkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSeatLink');
    }
}