<?php

/**
 * PluginSeatingPlanTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSeatingPlanTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSeatingPlanTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSeatingPlan');
    }
}