<?php

/**
 * PluginVatTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginVatTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginVatTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginVat');
    }
}