<?php

/**
 * PluginMetaEventTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginMetaEventTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginMetaEventTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginMetaEvent');
    }
}