<?php

/**
 * PluginManifestationWorkspaceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginManifestationWorkspaceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginManifestationWorkspaceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginManifestationWorkspace');
    }
}