<?php

/**
 * PluginColorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginColorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginColorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginColor');
    }
}