<?php

/**
 * PluginSeatTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSeatTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSeatTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSeat');
    }
}