<?php

/**
 * PluginHold
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Baptiste SIMON <baptiste.simon AT e-glop.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginHold extends BaseHold
{
  public function getIndexesPrefix()
  {
    return strtolower(get_class($this));
  }
  
  public function actAs($tpl, array $options = array())
  {
    $options['table'] = $this->getTable();
    return parent::actAs($tpl, $options);
  }
  
  public function setUp()
  {
    parent::setUp();
    
    // versions
    // adding a "lang" column to EventVersion to be able to record the changes in the i18n data
    $this->getTable()->getTemplate('Versionable')->getAuditLog()
      ->hasColumn('lang', 'string', 2, array('fixed' => true, 'primary' => true));
  }
}
