<?php

/**
 * PluginSeatedPlanWorkspaceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSeatedPlanWorkspaceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSeatedPlanWorkspaceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSeatedPlanWorkspace');
    }
}