<?php

/**
 * PluginEventCompanyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginEventCompanyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginEventCompanyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginEventCompany');
    }
}