<?php

/**
 * PluginEventCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginEventCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginEventCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginEventCategory');
    }
}