<?php

/**
 * PluginPlaceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPlaceTable extends LocationTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPlaceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPlace');
    }
}