<?php

/**
 * PluginSeatedPlanTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSeatedPlanTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSeatedPlanTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSeatedPlan');
    }
}