<?php

/**
 * PluginHoldTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginHoldTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginHoldTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginHold');
    }
}