<?php

/**
 * PluginUserPriceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUserPriceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginUserPriceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginUserPrice');
    }
}