<?php

/**
 * PluginPrice
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Baptiste SIMON <baptiste.simon AT e-glop.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginPrice extends BasePrice
{
  public function actAs($tpl, array $options = array())
  {
    $options['table'] = $this->getTable();
    return parent::actAs($tpl, $options);
  }
  public function getIndexesPrefix()
  {
    return strtolower(get_class($this));
  }
  
  public function preInsert($event)
  {
    $this->rank = $this->getTable()->createQuery('p')
      ->orderBy('p.rank DESC')
      ->limit(1)
      ->select('p.id, p.rank')
      ->fetchOne()
      ->rank * 2
    ;
    return parent::preInsert($event);
  }
}
