<?php

/**
 * PluginPricePOSTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPricePOSTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPricePOSTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPricePOS');
    }
}