<?php

/**
 * PluginWorkspacePriceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWorkspacePriceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWorkspacePriceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWorkspacePrice');
    }
}