<?php

/**
 * PluginPriceGaugeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPriceGaugeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPriceGaugeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPriceGauge');
    }
}