<?php

/**
 * PluginWebOriginTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWebOriginTable extends TraceableTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWebOriginTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWebOrigin');
    }
}