<?php

/**
 * PluginAutoGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginAutoGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginAutoGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginAutoGroup');
    }
}