<?php

/**
 * PluginSurveyOptionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSurveyOptionsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSurveyOptionsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSurveyOptions');
    }
}