<?php

/**
 * PluginSurveyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSurveyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSurveyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSurvey');
    }
}