<?php

/**
 * PluginSurveyAnswer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Baptiste SIMON <baptiste.simon AT e-glop.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginSurveyAnswer extends BaseSurveyAnswer
{
  public function save(Doctrine_Connection $conn = null)
  {
    // deal with multi-choices answers...
    if ( is_array($this->value) && count($this->value) > 0 )
    {
      $answers = new Doctrine_Collection('SurveyAnswer');
      $answers[] = $this;
      $pkeys = $this->getTable()->getIdentifier();
      
      $values = $this->value;
      foreach ( $values as $i => $value )
      {
        if ( !is_array($pkeys) )
          $pkeys = array($pkeys);
        $pkeys[] = 'value';
        foreach ( $this->getTable()->getColumns() as $column => $def )
        if ( !in_array($column, $pkeys) )
          $answers[$i]->$column = $this->$column;
        
        $answers[$i]->value = $value;
      }
      
      return $answers->save();
    }
    
    // to avoid saving empty answers
    if ( trim($this->value) )
      return parent::save($conn);
    
    $this->delete();
    return;
  }
  public function getIndexesPrefix()
  {
    return strtolower(get_class($this));
  }
}
