<?php

/**
 * PluginWebOriginIpTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWebOriginIpTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWebOriginIpTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWebOriginIp');
    }
}