<?php

/**
 * PluginSurveyAnswerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSurveyAnswerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSurveyAnswerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSurveyAnswer');
    }
}