<?php

/**
 * PluginRemoteAuthenticationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginRemoteAuthenticationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginRemoteAuthenticationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginRemoteAuthentication');
    }
}