<?php

/**
 * PluginSurveyQueryOptionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSurveyQueryOptionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSurveyQueryOptionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSurveyQueryOption');
    }
}