<?php

/**
 * PluginSurveyApplyToTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSurveyApplyToTable extends TraceableTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSurveyApplyToTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSurveyApplyTo');
    }
}