<?php

/**
 * PluginBankPaymentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginBankPaymentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginBankPaymentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginBankPayment');
    }
}