<?php

/**
 * PluginSlavePingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSlavePingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSlavePingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSlavePing');
    }
}