<?php

/**
 * MemberCardPriceModelTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MemberCardPriceModelTable extends PluginMemberCardPriceModelTable
{
  public function retrieveList()
  {
    return $this->createQuery('mcpm')
      ->leftJoin('mcpm.MemberCardType mct')
      ->leftJoin('mcpm.Price p');
  }
  
  public static function getInstance()
  {
      return Doctrine_Core::getTable('MemberCardPriceModel');
  }
}
