<?php

/**
 * MemberCardTypePromoCodeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MemberCardTypePromoCodeTable extends PluginMemberCardTypePromoCodeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object MemberCardTypePromoCodeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MemberCardTypePromoCode');
    }
}