<?php

/**
 * MemberCardPriceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MemberCardPriceTable extends PluginMemberCardPriceTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object MemberCardPriceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MemberCardPrice');
    }
}