<?php

/**
 * MemberCardTypeUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MemberCardTypeUserTable extends PluginMemberCardTypeUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object MemberCardTypeUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MemberCardTypeUser');
    }
}