<?php

/**
 * MemberCardType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class MemberCardType extends PluginMemberCardType
{
  public function getDescriptionName()
  {
    return trim(trim($this->description) ? $this->description : $this->name);
  }
  
  public function getRealValue()
  {
    if ( !$this->product_declination_id )
      return $this->value;
    
    $val = 0;
    foreach ( $this->ProductDeclination->Product->PriceProducts as $pp )
    if ( $pp->price_id == $this->price_id )
      $val = $pp->value;
    return $this->value + $val;
  }
}
