<?php

/**
 * PluginAccounting
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Baptiste SIMON <baptiste.simon AT e-glop.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginAccounting extends BaseAccounting
{
  public function getIndexesPrefix()
  {
    return strtolower(get_class($this));
  }
  
  public function preSave($event)
  {
    // verifying if every ticket has a price_id
    $q = Doctrine::getTable('Ticket')->createQuery('tck')
      ->andWhere('tck.transaction_id = ?', $this->transaction->id)
      ->andWhere('tck.price_id IS NULL');
    if ( $q->count() > 0 )
      throw new liBookingException("No accounting document can be created (or even modified) if some tickets are still running without price_id for its transaction (here: #".$this->transaction->id.")");
    
    parent::preSave($event);
  }
}
