<?php

/**
 * PluginPaymentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPaymentTable extends TraceableTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPaymentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPayment');
    }
}