<?php

/**
 * PluginCancellationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCancellationTable extends TraceableTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginCancellationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginCancellation');
    }
}