<?php

/**
 * PluginTaxManifestationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTaxManifestationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTaxManifestationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTaxManifestation');
    }
}