<?php

/**
 * PluginMemberCardPriceModelTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginMemberCardPriceModelTable extends TraceableTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginMemberCardPriceModelTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginMemberCardPriceModel');
    }
}