<?php

/**
 * PluginContactEventArchivesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginContactEventArchivesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginContactEventArchivesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginContactEventArchives');
    }
}