<?php

/**
 * PluginAccountingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginAccountingTable extends TraceableTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginAccountingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginAccounting');
    }
}