<?php

/**
 * PluginTaxPriceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTaxPriceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTaxPriceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTaxPrice');
    }
}