<?php

/**
 * PluginPaymentMethodTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPaymentMethodTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPaymentMethodTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPaymentMethod');
    }
}