<?php

/**
 * PluginOrderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginOrderTable extends TraceableTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginOrderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginOrder');
    }
}