<?php

/**
 * PluginOptionAccountingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginOptionAccountingTable extends OptionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginOptionAccountingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginOptionAccounting');
    }
}