<?php

/**
 * PluginRawAccountingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginRawAccountingTable extends TraceableTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginRawAccountingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginRawAccounting');
    }
}