<?php

/**
 * PluginTransactionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTransactionTable extends TraceableTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTransactionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTransaction');
    }
}