<?php

/**
 * PluginControlTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginControlTable extends TraceableTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginControlTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginControl');
    }
}