<?php

/**
 * PluginTaxUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTaxUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTaxUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTaxUser');
    }
}