<?php

/**
 * PluginTicketTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTicketTable extends TraceableTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTicketTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTicket');
    }
}