<?php

/**
 * AccountingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AccountingTable extends PluginAccountingTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object AccountingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Accounting');
    }
    
    public function fetchOneById($id)
    {
      return $this->createQuery('a')->andWhere('id = ?',$id)->fetchOne();
    }
}
