<?php

/**
 * CancellationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CancellationTable extends PluginCancellationTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object CancellationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cancellation');
    }
}