<?php

/**
 * ControlTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ControlTable extends PluginControlTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ControlTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Control');
    }
}