<?php

/**
 * ContactEventArchivesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContactEventArchivesTable extends PluginContactEventArchivesTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContactEventArchivesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ContactEventArchives');
    }
}
