<?php

/**
 * Control
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Baptiste SIMON <baptiste.simon AT e-glop.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $sfConfig::get('app_tickets_id')sfConfig::get('app_tickets_id')
 */
class Control extends PluginControl
{
  public function preSave($event)
  {
    if ( ($field = sfConfig::get('app_tickets_id', 'id')) != 'id' )
    {
      if ( intval($this->ticket_id).'' === ''.$this->ticket_id )
        $field = 'id';
      
      $past = sfConfig::get('app_control_past') ? sfConfig::get('app_control_past') : '6 hours';
      $future = sfConfig::get('app_control_future') ? sfConfig::get('app_control_future') : '1 day';

      error_log($this->ticket_id);
      $q = Doctrine::getTable('Ticket')->createQuery('t')
        ->leftJoin('t.Manifestation m')
        ->andWhere('t.'.$field.' = ?',$this->ticket_id)
        ->andWhere('t.manifestation_id IN (SELECT mm.id FROM checkpoint c LEFT JOIN c.Event e LEFT JOIN e.Manifestations mm WHERE c.id = ?)',$this->checkpoint_id)
        ->andWhere('m.happens_at < ?',date('Y-m-d H:i',strtotime('now + '.$future)))
        ->andWhere('m.happens_at >= ?',date('Y-m-d H:i',strtotime('now - '.$past)))
        ->andWhere('t.integrated_at IS NOT NULL OR t.printed_at IS NOT NULL')
        ->orderBy('m.happens_at');
      
      if (!( $ticket = $q->fetchOne() ))
        throw new liEvenementException('No ticket found for this Control...');

      $this->ticket_id = $ticket->id;
    }
    
    return parent::preSave($event);
  }
}
