<?php

/**
 * HoldTransactionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HoldTransactionTable extends PluginHoldTransactionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object HoldTransactionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HoldTransaction');
    }
}