<?php

/**
 * MemberCardPrice
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class MemberCardPrice extends PluginMemberCardPrice
{
  public function __toString()
  {
    $str = (string)$this->Price;
    return $str;
  }
}
