<?php

/**
 * MemberCardPriceModelTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MemberCardPriceModelTable extends PluginMemberCardPriceModelTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object MemberCardPriceModelTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MemberCardPriceModel');
    }
}