<?php

/**
 * Payment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Baptiste SIMON <baptiste.simon AT e-glop.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Payment extends PluginPayment
{
  public function preDelete($event)
  {
    if ( !is_null($this->member_card_id) )
    {
      $this->MemberCard->value += $this->value;
      $this->MemberCard->save();
    }
    parent::preDelete($event);
  }
  
  public function save(Doctrine_Connection $conn = null)
  {
    if ( $this->Method->member_card_linked )
    {
      foreach ( $this->Transaction->Contact->MemberCards as $card )
      if ( strtotime($card->expire_at) > strtotime('now')
        && strtotime('now') > strtotime($card->created_at)
        && $card->value >= $this->value  )
        break;
      else
        $card = NULL;

      if ( !is_null($card) )
      {
        $card->value -= $this->value;
        $card->save();
        $this->MemberCard = $card;
      }
    }
    
    if ( is_null($this->member_card_id) && $this->Method->member_card_linked )
      throw new sfDatabaseException('No MemberCard linked with this Payment whereas its Method requires it.');
    
    parent::save($conn);
  }
}
