<?php

/**
 * RawAccountingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RawAccountingTable extends PluginRawAccountingTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object RawAccountingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RawAccounting');
    }
}