<?php

/**
 * SellerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SellerTable extends PluginSellerTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object SellerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Seller');
    }
}