<?php

/**
 * TaxUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TaxUserTable extends PluginTaxUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object TaxUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TaxUser');
    }
}