<?php

/**
 * TicketTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TicketTable extends PluginTicketTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object TicketTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Ticket');
    }
  
  public function createQuery($alias = 'tck')
  {
    return parent::createQuery($alias)
      ->leftJoin("$alias.Duplicatas duplicatas");
  }
}
