<?php

/**
 * TicketTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TicketTable extends PluginTicketTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object TicketTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Ticket');
    }
  
  public function createQuery($alias = 'tck')
  {
    return parent::createQuery($alias)
      ->leftJoin("$alias.Duplicatas duplicatas");
  }
  
  public function createQueryPreparedForRanks($alias = 'tck')
  {
    return parent::createQuery($alias)
      ->leftJoin("$alias.Seat {$alias}_s")
      ->andWhere("$alias.printed_at IS NOT NULL OR $alias.integrated_at IS NOT NULL")
      ->andWhere("$alias.seat_id IS NOT NULL")
      
      ->leftJoin("$alias.Transaction {$alias}_t")
      
      //->having("{$sql_fct}({$alias}_s.rank) $operand $value")
      //->groupBy("{$alias}_t.contact_id')
    ;
  }
}
