<?php

/**
 * BaseEntryTickets
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $entry_element_id
 * @property integer $price_id
 * @property integer $quantity
 * @property EntryElement $EntryElement
 * @property Price $Price
 * 
 * @method integer      getEntryElementId()   Returns the current record's "entry_element_id" value
 * @method integer      getPriceId()          Returns the current record's "price_id" value
 * @method integer      getQuantity()         Returns the current record's "quantity" value
 * @method EntryElement getEntryElement()     Returns the current record's "EntryElement" value
 * @method Price        getPrice()            Returns the current record's "Price" value
 * @method EntryTickets setEntryElementId()   Sets the current record's "entry_element_id" value
 * @method EntryTickets setPriceId()          Sets the current record's "price_id" value
 * @method EntryTickets setQuantity()         Sets the current record's "quantity" value
 * @method EntryTickets setEntryElement()     Sets the current record's "EntryElement" value
 * @method EntryTickets setPrice()            Sets the current record's "Price" value
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Baptiste SIMON <baptiste.simon AT e-glop.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEntryTickets extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('entry_tickets');
        $this->hasColumn('entry_element_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('price_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('quantity', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));


        $this->index('entry_price_index', array(
             'fields' => 
             array(
              0 => 'entry_element_id',
              1 => 'price_id',
             ),
             'unique' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('EntryElement', array(
             'local' => 'entry_element_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('Price', array(
             'local' => 'price_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}