<?php

/**
 * PluginTypeOfResourcesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTypeOfResourcesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTypeOfResourcesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTypeOfResources');
    }
}