<?php

/**
 * PluginContactRelationshipTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginContactRelationshipTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginContactRelationshipTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginContactRelationship');
    }
}