<?php

/**
 * PluginGeoFrDepartmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginGeoFrDepartmentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginGeoFrDepartmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginGeoFrDepartment');
    }
}