<?php

/**
 * PluginGroupProfessionalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginGroupProfessionalTable extends GroupDetailTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginGroupProfessionalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginGroupProfessional');
    }
}