<?php

/**
 * PluginAddressableTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginAddressableTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginAddressableTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginAddressable');
    }
}