<?php

/**
 * PluginContactRelationship
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginContactRelationship extends BaseContactRelationship
{
  public function save(Doctrine_Connection $con = NULL)
  {
    if ( !$this->to_contact_id )
      return false;
    parent::save($con);
  }
}
