<?php

/**
 * PluginMemberCardTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginMemberCardTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginMemberCardTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginMemberCard');
    }
}