<?php

/**
 * PluginContactArchiveTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginContactArchiveTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginContactArchiveTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginContactArchive');
    }
}