<?php

/**
 * PluginGeoFrRegionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginGeoFrRegionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginGeoFrRegionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginGeoFrRegion');
    }
}