<?php

/**
 * PluginOrganismCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginOrganismCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginOrganismCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginOrganismCategory');
    }
}