<?php

/**
 * PluginPhoneTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPhoneTypeTable extends ModelTypeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPhoneTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPhoneType');
    }
}