<?php

/**
 * PluginProfessionalTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginProfessionalTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginProfessionalTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginProfessionalType');
    }
}