<?php

/**
 * PluginOptionLabelsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginOptionLabelsTable extends OptionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginOptionLabelsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginOptionLabels');
    }
}