<?php

/**
 * PluginGroupContactTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginGroupContactTable extends GroupDetailTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginGroupContactTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginGroupContact');
    }
}