<?php

/**
 * PluginPhonenumberTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPhonenumberTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPhonenumberTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPhonenumber');
    }
}