<?php

/**
 * PluginProfessionalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginProfessionalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginProfessionalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginProfessional');
    }
}