<?php

/**
 * PluginFamilialQuotientTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginFamilialQuotientTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginFamilialQuotientTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginFamilialQuotient');
    }
}