<?php

/**
 * PluginProfessionalArchiveTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginProfessionalArchiveTable extends ProfessionalTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginProfessionalArchiveTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginProfessionalArchive');
    }
}