<?php

/**
 * PluginOptionCsvTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginOptionCsvTable extends OptionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginOptionCsvTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginOptionCsv');
    }
}