<?php

/**
 * PluginOrganismPhonenumberTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginOrganismPhonenumberTable extends PhonenumberTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginOrganismPhonenumberTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginOrganismPhonenumber');
    }
}