<?php

/**
 * PluginContactPhonenumberTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginContactPhonenumberTable extends PhonenumberTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginContactPhonenumberTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginContactPhonenumber');
    }
}