<?php

/**
 * PluginOptionMandatoryFieldTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginOptionMandatoryFieldTable extends OptionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginOptionMandatoryFieldTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginOptionMandatoryField');
    }
}