<?php

/**
 * PluginProfessional
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Baptiste SIMON <baptiste.simon AT e-glop.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginProfessional extends BaseProfessional
{
  public function preDelete($event)
  {
    $backup = new ProfessionalArchive;
    foreach ( $this->getData() as $field => $value )
      $backup->$field = $value;
    $backup->updated_at = date('Y-m-d H:i:s');
    $backup->save();
    return parent::preDelete($event);
  }
}
