<?php

/**
 * PluginContactRelationshipTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginContactRelationshipTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginContactRelationshipTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginContactRelationshipType');
    }
}