<?php

/**
 * PluginFamilialSituationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginFamilialSituationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginFamilialSituationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginFamilialSituation');
    }
}